### PR TITLE
Site Tour: Add Tour link

### PR DESCRIPTION
**Pull request by trymebytes**
## Problem

We need to be able to view a list of available tours on the translations page

## Solution

Add a "Tour" link which when clicked displays a list of available tours on the page.

## Screenshots or screencast
tour_link

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
The Glossary don't exist sitewide. I suggest adding it to the ul.breadcrumb bar, below the navigation.

**Comment by trymebytes** [comment]
> The Glossary don't exist sitewide. I suggest adding it to the ul.breadcrumb bar, below the navigation.

Nice observation, thank you!

**Comment by akirk** [comment]
Should clicking the tour do anything yet?

**Comment by akirk** [comment]
Regarding Pedro's concern, I do like the postion but was wondering if we could wrap the `glossary-links` div with a new one like `meta-links` and could then add the tour link to that div.

**Comment by trymebytes** [comment]
Closed in favour of the Tour plugin which already has this feature.

**Pull request closed without merging**
