### PR TITLE
Build minified assets

### PR DESCRIPTION
**Pull request by pedro-mendonca**
## Problem
The release 4.0.0-alpha.5 doesn't include the updated minified JavaScript and CSS.

## Solution
Run npm build

### CODE REVIEW

**Comment by trymebytes** [comment]
Works for me!

**Comment by pedro-mendonca** [comment]
@trymebytes since https://github.com/GlotPress/GlotPress/pull/1369 many JS was changed, and as we've discussed, the PRs shouldn't include the minified versions.
For this, a build step must be added before releases.
Related to https://github.com/GlotPress/GlotPress/issues/1587

**Review by trymebytes — APPROVED** [review]

**Comment by akirk** [comment]
Closing this in favor of #1654.

**Comment by pedro-mendonca** [comment]
@akirk the minified assets in the repo remain old. #1654 and #1655 just build the files for deploying.
Until isn't decided if minified assets should be kept on the repo (#1587), shouldn't at least be kept updated?

**Pull request closed without merging**
