### PR TITLE
415: URL encode the project path.

### LINKED ISSUE #415: Using utf8mb4 chars as names/slugs of projects can't be found
Steps to reproduce:
- Have a database which supports utf8mb4 encoding
- Create a project with 🌍 as the title

### PR DESCRIPTION
**Pull request by toolstack**
Make sure to urlencode the project path to match a slug with a UTF8 character in it.

Resolves #415.

### CODE REVIEW

**Comment by toolstack** [comment]
Note the TravisCI failure is expected as `urlencode()` is no longer recommended, but since we have used it in the slug sanitization code, and the results are stored in the database as the slug, we have to use it here as well.

**Review by Mte90 — APPROVED** [review]

**Comment by Mte90** [comment]
We have a ticket for `url_encode` to remove/replace it? just to not forget it.

**Comment by toolstack** [comment]
No ticket to replace `urlencode()` as we'd break any project that differed from the values generated between it and `rawurlencode()`.

That's probably a small subset of projects, but it would be very difficult to mitigate and whille `urlencode()` is no longer recommended, it still works and there is no expectation that it will break (it does generate valid links, just not RFC3986 compliant ones).

It's something we need to watch out for, and if at some point we revisit the slug/path code we should handle it at that time.

**Comment by Mte90** [comment]
Ok no problem.

**Pull request merged**
