### PR TITLE
Update Locales list from wp.org

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Get latest Locale list from [translate.wordpress.org](https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php?rev=8424)

- [x] Add missing `wp_locale` to *Kurdish (Kurmanji)* -> `kmr`
- [x] Rename ~English (Unites States)~ -> English
- [x] Add the follow Locales:

| Name | wp_locale | [/locales/locales.php](https://github.com/GlotPress/GlotPress-WP/blob/develop/locales/locales.php) | [/locales/no-variants/locales.php](https://github.com/GlotPress/GlotPress-WP/blob/develop/locales/no-variants/locales.php) |
| --- | --- | :---: | :---: |
| Bhojpuri  | `bho`  | ✔️ | ✔️ |
| Bodo | `brx` | ✔️ | ✔️ |
| German (Austria) | `de_AT` | ✔️ | ✔️ |
| Spanish (Dominican Republic) | `es_DO` | ✔️ | ✔️ |
| Spanish (Honduras) | `es_HN`  | ✔️ | ✔️ |
| Upper Sorbian | `hsb` | ✔️ | ✔️ |
| Igbo | `ibo` | ✔️ | ✔️ |
| Karakalpak | `kaa` | ✔️ | ✔️ |  
| N’ko | `nqo` | ✔️ | ✔️ |
| Portuguese (Angola) | `pt_AO` | ✔️ | ✔️ |

### CODE REVIEW

**Comment by xavivars** [comment]
ca-valencia was added not that long ago to WP.org locales file, and it'd be great to have it here. Also, it should be a variant of Catalan, in order to leverage all the existing translations of strings that won't change. Should this be part of this PR?

**Comment by pedro-mendonca** [comment]
Hi @xavivars,
In this pull request I've just added the current missing main locales, not the variants.
The main reason I didn't include the current wp.org variants is because they are somehow pseudo-variants, not the future completely supported variants currently being developed in GlotPress.
I guess in a near future, when variants are trully supported in GlotPress, the current pseudo-variants in wp.org will be changed.
If one of the reviewers can confirm this, maybe we can temporarily add the current pseudo-variants to the /no-variants/locales.php too, at least until GP have real support for variants.

**Review by ocean90 — APPROVED** [review]

**Comment by xavivars** [comment]
@pedro-mendonca the reason I was asking is because, as far as I know, variants are already supported in GlotPress (see https://github.com/GlotPress/GlotPress-WP/pull/747).

We haven't started translating ca-valencia yet in WordPress.org because we don't want people to face the problem of having core translated but everything else (plugins, themes) not, and are waiting for GlotPress 3.0 to be released and deployed at WordPress.org to start.

But I thought that, given the variant feature is already merged, we could start adapting GlotPress locale file to be prepared.

@ocean90 any thoughts? I can put together a PR if you guys think that's the right thing to do

**Comment by pedro-mendonca** [comment]
@xavivars yes it's already in the develop branch, but it's not released yet, and the translate.wp.org does not have this new developed variant support, it's an old pseudo-variant.
I'm not sure what would be fast to evaluate, add pseudo-variants to GP, or release the GP 3.0 and bring the new variants support to wp.org.

I think adding a new PR with that to start preparing the current pseudo-variants to the new variant feature is a good idea.

**Comment by ocean90** [comment]
The way how w.org defines variants (and which #226 was actually requesting) differs from how variants are handled in the develop branch. So the variants from w.org won't help here.

**Pull request merged**
