### PR TITLE
Highlight leading and trailing spaces, and double/multiple spaces in the middle

### LINKED ISSUE #863: Highlight trailing spaces
PoEdit highlights the space if it is (non-visible) after the end of the text:

bildschirmfoto 2015-10-19 um 11 09 17

If this is not working technically. We could add an warning in this case (if we don't do this already).

Related: https://github.com/GlotPress/GlotPress-WP/issues/801

### LINKED ISSUE #1499: Add a color mark in the white spaces at the begging and at the end of an original and a translation
Sometimes, the original string has white spaces at the begging and/or at the end. It happens the same with the translation. This issue proposes to add some color mark to show to the translator that the original and/or the translation has some white spaces at the begging and/or at the end.

See this image from [Poedit](https://poedit.net/) (props @pedro-mendonca).

image

More context in the [discussion](https://wordpress.slack.com/archives/C02RP4R9F/p1664959057106449) in the GlotPress monthly meeting.

### PR DESCRIPTION
**Pull request by pedro-mendonca**
## What?
Highlight the leading and trailing spaces both in the preview and editor rows
Also highlight double and multiple spaces in the middle.

This PR also adds a missing unit test for the invisible characters markup added on [prepare_original()](https://github.com/GlotPress/GlotPress/blob/develop/gp-templates/helper-functions.php#L17) for line breaks and tabs.

## Why?
Allows the translator to see the spaces at the beginning or the end of an original/translation.
Allows authors and translators to see double and multiple spaces in the middle of strings.

## How?
Wrap the spaces in a `<span>` with `invisible-spaces` class, which adds a grey color.

## Testing Instructions

1. Have some original string with spaces in the beginning or end, or with double spaces in the middle
2. Open the translation set where the string appears, see the highlighted spaces in grey in the preview row, both in original and preview (since https://github.com/GlotPress/GlotPress/pull/1500/commits/7a31b0fcab7db6b2502add1d52cec711fa08168a)
3. Open the translation string editor and see the highlighted spaces in grey, both in the original and translation.

imagem

imagem

Fixes #863.

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
@amieiro currently the Translation markup is added to editor `<blockquote>` through `prepare_original()`, which is probably wrong because also searches for glossary etc.
To add it to both the translation bloquote and preview row, maybe is better to use another function (`prepare_translation_preview()`) and add the highlight to it.

**Comment by pedro-mendonca** [comment]
Using the `prepare_original()` in the translation of the preview row, as it's used for the current translation blockquote above the textarea, adds the markup. This function still uncessasry searches for glossary entries, but none will be found.

imagem

**Comment by pedro-mendonca** [comment]
Added support for strings with multiple lines:
imagem

**Comment by pedro-mendonca** [comment]
Adding another highlight: **double/multiple spaces between words**.

imagem

Changing the CSS to a darker color with opacity 50% so it works better on different backgrounds of the string status:

imagem

**Comment by pedro-mendonca** [comment]
Added unit tests for both the spaces highlight introduced in this PR, and the already existent markup for invisible characters as tabs and line breaks

**Comment by akirk** [comment]
We agreed on our triage session that this can be merged after a code review. The functionality is fine.

**Review by amieiro — APPROVED** [review]

**Comment by lmwp** [comment]
just ... thank you so much !!!

**Pull request merged**
