### PR TITLE
Enable plural forms for Persian languages

### PR DESCRIPTION
**Pull request by farhadsakhaei**
Hi,
We need to have plural and singular forms in our language So I deleted the settings to have default values

Regards

### CODE REVIEW

**Comment by amieiro** [comment]
The plural expression for Persian is `n > 1`. You can check it at:
- [Unicode CLDR v44.0](https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html). 
- [PHP gettext](https://php-gettext.github.io/Languages/).
- [Launchpad](https://translations.launchpad.net/+languages/fa).

In GlotPress, the [default expression](https://github.com/GlotPress/GlotPress/blob/10644fd9bebd966c1327ff7fea3879556be7833b/locales/locales.php#L15) for plurals is `n != 1`, that is different to the Persian language `n > 1`, available [here](https://github.com/GlotPress/GlotPress/blob/10644fd9bebd966c1327ff7fea3879556be7833b/locales/locales.php#L1024).

So the current Persian plural is correct in GlotPress. I have made a test in my local machine and it works fine.

image

The problem is at translate.wordpress.org. If you look for the [same Akismet string in Persian](https://translate.wordpress.org/projects/wp-plugins/akismet/stable/fa/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=1808107&filters%5Btranslation_id%5D=52506313), you only have one form, not 2.

image
 
The incorrect code is [here](https://github.com/WordPress/wordpress.org/blob/c48300cae7c36cce9d2cde982acb2137dc48f6b5/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L1034-L1035):

```php
$fa->nplurals = 1;
$fa->plural_expression = '0';
```

I think we should update it with the [GlotPress code](https://github.com/GlotPress/GlotPress/blob/10644fd9bebd966c1327ff7fea3879556be7833b/locales/locales.php#L1023-L1024):

```php
$fa->nplurals = 2;
$fa->plural_expression = 'n > 1';
```

I am going to ping in Slack to the current Persian GTE to get their opinion. Thank you for arising this problem.

**Comment by farhadsakhaei** [comment]
@amieiro
Thank you for your reply and detail review
Yes, Exactly,
I was wonder why we can't have 2 forms for singular and plural on translate.wordpress.org
I was requested before for this:
https://github.com/GlotPress/GlotPress/pull/1012
I am a Persian locale manager too

**Comment by ocean90** [comment]
WordPress.org has its own copy of `locales.php`, see https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php?rev=12939#L1027.

I think the change wasn't done because there's no migration step for such a change and existing translations may cause missing translations in WordPress. Probably something to test if this is still the case.

Closing the PR since the correct change was done in #1012.

**Comment by farhadsakhaei** [comment]
Hi @ocean90 ,
Thank you for your reply,
Actually both requests are made by me,
I was wonder why previous change didn't apply in the translate.wordpress.org
now @amieiro mentioned a good point,
The previous change didn't apply on the wordpress site (translate) itself:

https://github.com/WordPress/wordpress.org/blob/c48300cae7c36cce9d2cde982acb2137dc48f6b5/wordpress.org/public_html/wp-content/mu-plugins/pub/locales/locales.php#L1034-L1035

It was applied on the glotpress source only:

https://github.com/GlotPress/GlotPress/blob/10644fd9bebd966c1327ff7fea3879556be7833b/locales/locales.php#L1023-L1024

And yes, the correct format is :
```
$fa->nplurals = 2;
$fa->plural_expression = 'n > 1';
```

**Pull request closed without merging**
