### PR TITLE
Add new Pirate English locale

### PR DESCRIPTION
**Pull request by danieltj27**
Please add a new locale for English (Pirate).

This is based off of the original request in PR #832.

I've also altered the locale code to match up with existing locales of the same name. Facebook refers to it as `en_PI` so I suggest keeping the locale code the same for compatibility.

See #828.

### CODE REVIEW

**Review by itssimple — APPROVED** [review]
Looks good to me.

**Review by ocean90 — COMMENTED** [review]
Proposal based on the Emoji locale:

```php
$pirate = new GP_Locale();
$pirate->english_name = 'English (Pirate)';
$pirate->native_name = 'English (Pirate)';
$pirate->lang_code_iso_639_2 = 'art';
$pirate->wp_locale = 'art_xpirate';
$pirate->slug = 'en-pi';
$pirate->google_code = 'xx-pirate';
$pirate->facebook_locale = 'en_PI';
```

`art` is for artificial languages.

**Comment by danieltj27** [comment]
Sure thing, I'll amend the PR when I have a spare moment 👍

**Comment by danieltj27** [comment]
Trying to figure out how to update this PR.

Made the changes here: https://github.com/danieltj27/GlotPress-WP/commit/63db8c662ce922d97836c43740a649d24c50e83b

**Comment by toolstack** [comment]
Might be easier to do a new PR if it's giving you problems merging in the changes to this tree.

**Comment by danieltj27** [comment]
Ah, sorry. It looks like the commits are sorted in ascending order so I didn't see it at the bottom.

Oh dear... okay well it should be update now in this PR ready for review 👍

**Review by ocean90 — CHANGES_REQUESTED** [review]
Don't worry about the merging, we can squash and merge it for you.

Just noticed that I forgot to change the `slug` property. If we follow Emoji it would be `art-xpirate` but I'd be fine with just `pirate` though. Since the list is sorted alphabetically it should be moved before the Polish locale.

**Comment by danieltj27** [comment]
Okay I can make the change later on. I think it’s probably best to keep it the same as Emoji so it’s `art-pirate`.

**Comment by danieltj27** [comment]
@ocean90 updated the slug for Pirate to `art-xpirate` and moved above Polish locale. 👍

**Review by ocean90 — APPROVED** [review]

**Pull request merged**
