### PR TITLE
Update the minimum PHP version to 7.4 in composer.json and phpcs.xml.dist files

### PR DESCRIPTION
**Pull request by amieiro**
## Problem

GlotPress has updated minimum required PHP version to 7.4 ([#1417](https://github.com/GlotPress/GlotPress/commit/82650030f7cad7d3e4bcee1e7f89ad3941912eb1)) but it has 2 files without this update.

## Solution
Update the references to the PHP version from 7.2 to 7.4 in these files:

* composer.json.
* phpcs.xml.dist.

### CODE REVIEW

**Review by ocean90 — CHANGES_REQUESTED** [review]
Can you remove the package updates?

**Comment by amieiro** [comment]
Removed the package updates. 
The tests were failing due to the `gettext/languages` upgrade. @akirk [has reverted it](https://github.com/GlotPress/GlotPress/pull/1418/commits/bd5973d312de7c523812e424cd4b4a4dc4219954), so the CI system is working now.

**Comment by akirk** [comment]
That update of `gettext/languages` [upgrades CLDR 39 to 40](https://github.com/php-gettext/Languages/pull/44) which causes the failures. We need to investigate (best in a new PR) what to do about those updated plurals. Also the changes to tests should go into a new PR.

**Comment by ocean90** [comment]
I have cherry-picked the version update into #1419. For the update of gettext/languages we already have #1296.

**Pull request closed without merging**
