### PR TITLE
Add a template for the PR

### PR DESCRIPTION
**Pull request by amieiro**
This PR adds a template for the PR, so the person who sends the PR has to explain a few details around the PR, and the maintainer will have more information to review it.

More info about template PR on GitHub can be found [here](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository).

### CODE REVIEW

**Comment by ocean90** [comment]
I think we should have a more simple template without any checkboxes. See https://github.com/WordPress/gutenberg/pull/39229 and https://github.com/WordPress/gutenberg/issues/40470 for some background.

**Comment by amieiro** [comment]
Could be interesting to copy [this template](https://raw.githubusercontent.com/WordPress/gutenberg/trunk/.github/PULL_REQUEST_TEMPLATE.md), adapting it to GlotPress?

**Review by ocean90 — APPROVED** [review]

**Comment by pedro-mendonca** [comment]
What about an optional footer link for an existing related issue that gets fixed with the PR?

Example:
Fixes #[issue-number]

**Comment by amieiro** [comment]
> What about an optional footer link for an existing related issue that gets fixed with the PR?
> 
> Example: Fixes #[issue-number]

If we want a simple template, I think this could be added in the `## Why?` section. The template adds HTML comments with this information, as you can see in the next screenshot.

image

**Comment by pedro-mendonca** [comment]
Great, missed that :)

**Pull request merged**
