### PR TITLE
801: Add warnings for hard non-breaking spaces in translations.

### LINKED ISSUE #801: Highlight non-breaking-space as hints for Translation Editors
We French translators have an issue with the non-breaking-space character which we use regularly in punctuation. 

When the character is not produced with &nbsp; HTML entity, but with ALT+255 or ALT+SPACE (which I guess is better), Translation Editors can not see it on Translate and thus can not check its presence (it must replace normal spaces in special case for punctuation) during validation process.

I started to work on a JS script for browser's console to highlight these characters but I wonder if this should not be integrated on GlotPress.

So I worked on a JS patch:
`
jQuery('tr.preview > td.translation.foreign-text').each(function(){
	var translation_item = jQuery(this).text();
	if ( translation_item.indexOf(' ') > -1 ) {
		var translation_highlighted = '';
		for (var i = 0; i < translation_item.length; i++) {
			if (translation_item[i] == ' ') {
				translation_highlighted += '<span style="background-color:yellow"> </span>';
			} else {
				translation_highlighted += translation_item[i];
			}
		}
		jQuery(this).html(translation_highlighted);
	}
});
`
I made this outside this repo, only in my browser, so it should needs some unit tests 😄 

Result: 
result

### PR DESCRIPTION
**Pull request by toolstack**
Resolves #801.

### CODE REVIEW

**Comment by ocean90** [comment]
I'm not really sure what you mean by "hard non-breaking space" because I can't get this working. 🤔 
On macOS I'm using Option + Space to enter a non-breaking space but I don't get a warning.

Is this about the UTF-8 version of the non-breaking space? If so we should probably use `"\xC2\xA0"` here (`substr_count( $translation, "\xC2\xA0" );`). That's at least working for me.

What's the reason for not counting nbsp entities as well?

**Comment by toolstack** [comment]
This is around specifically ascii 255, which looks like a space character but technically isn't a space.

You could throw another warning/error if there was a missing html nbsp entity (assuming we don't already) but this PR wasn't to address that.

**Comment by ocean90** [comment]
Still missing the "hard" part here. How does one enter the character? Isn't 255 just a regular non-breaking space?

**Comment by toolstack** [comment]
Hard as in hard to enter ;)  

Hard as in not an html entity.

**Comment by ocean90** [comment]
So, what's the difference between `"\xC2\xA0"` (works for me)  and `chr( 255 )` (doesn't work for me)?

**Comment by SergeyBiryukov** [comment]
Interesting, I always thought that 160 decimal (A0 hex) is the code for non-breaking space in extended ASCII encodings rather than 255 decimal (FF hex).

Per [Wikipedia](https://en.wikipedia.org/wiki/Non-breaking_space), it's both:
> Non-breaking space has codepoint 255 decimal (FF hex) in codepage 437 and codepage 850, and codepoint 160 decimal (A0 hex) in codepage 1252.

**Pull request closed without merging**
