### PR TITLE
Change string for consistency

### PR DESCRIPTION
**Pull request by pedro-mendonca**
Rename "with warnings" to comply with the filter string "Warnings"

### CODE REVIEW

**Comment by toolstack** [comment]
I'm not sure "Warnings" is the right term here as being consistent with the other items in the legend may not be the best solution.

The other legend items are all mutually exclusive, aka you can't have "Current" and "Waiting", but you can have "Current" and "with warnings".

"with warnings" is a modifier of the other items, so while "with warnings" may not be the best, it doesn't have to be the same as the others.

Perhaps "has Warnings" or "Warnings present" or something else?

**Comment by pedro-mendonca** [comment]
Comparison to other platforms:

Poedit uses *With errors*
Transifex uses *With issues*

**Comment by ocean90** [comment]
Attaching a screenshot so everyone knows what this is about:

legend

In this case it's about the label for the legend. I'd probably change it to "With warnings" (capital "W").

**Comment by ocean90** [comment]
@pedro-mendonca Do you want to update the PR to change the string to a capital "W"?

**Comment by pedro-mendonca** [comment]
@ocean90 of course -> "With Warnings"

**Comment by pedro-mendonca** [comment]
Done:
https://github.com/pedro-mendonca/GlotPress-WP/commit/e277978511a5bca4c9ae65127a0d3505f81a85f3

**Review by ocean90 — APPROVED** [review]

**Pull request merged**
