### PR TITLE
479: Provide an uninstall routine

### PR DESCRIPTION
**Pull request by amieiro**
This code is based on PR #513 and issue #479.

- Add a settings page menu for WordPress to confirm the data deletion.
- Delete all GlotPress database tables only if the confirmation check was selected.
- Delete all GlotPress settings in the WordPress options table.

### CODE REVIEW

**Review by ocean90 — CHANGES_REQUESTED** [review]
Thanks for working on this!

* Can we use two uninstall options here? One option allows the deletion of options and one for tables. For options I'd set the default to true.
* Can you make use of the `$args` argument for `register_setting` to define the default value, sanitize callback, group, etc?
* Can you please register a section "Uninstall" via `add_settings_section()`?
* Can you please use `add_settings_field()` to render the two checkboxes in the "Uninstall" section?
* Do we actually need a class or would be a few functions good enough too? I'm asking because already have some admin functionality [here](https://github.com/GlotPress/GlotPress-WP/blob/f55ca5a9cde6ee50902e6202ad6f3ed8b8c6ace4/gp-includes/misc.php#L531-L598).

Related resources: https://developer.wordpress.org/plugins/settings/settings-api/

**Comment by amieiro** [comment]
I have added 2 options: 
- One to delete the options.
- One to delete the data (tables).

By default, the first option is enabled and the second disabled.

GlotPress ‹ — WordPress 2021-09-20 19-54-49

I have maintained the new class, because I think the menu showed in the user profile is related with the user capabilities, not with the GlotPress configuration.

Profile ‹ — WordPress 2021-09-20 19-55-29

I have added the Options API functions (register_setting, add_settings_section, add_settings_field), the validation and all the needed callbacks.

**Comment by ocean90** [comment]
It looks like the branch got deleted?

**Comment by amieiro** [comment]
I think I have deleted the branch on my repository, but the code are on the PR commits. Can you access to the code, or do you need that I regenerate the commits?

**Comment by amieiro** [comment]
I close this PR because it continues in [this one](https://github.com/GlotPress/GlotPress-WP/pull/1388).
I have created the new one because I have deleted the previous branch in my GitHub fork.

**Pull request closed without merging**
