### PR TITLE
666: Add Android Plurals support

### LINKED ISSUE #666: Support plurals in Android exports
Currently GP does not support plurals in Android XML files, however the [standard](https://developer.android.com/guide/topics/resources/string-resource.html#Plurals) does provide support for them.

### PR DESCRIPTION
**Pull request by akirk**
This fixes #666. It is an alternative to the complex implementation of #784 that requires marking a project as having a CLDR or nplurals format.

This PR calculates a `cldr_plurals_mapping` for each locale and uses that when outputting files for Android. I cherry-picked most of the Android format changes from https://github.com/GlotPress/GlotPress-WP/pull/784/commits/8a3002c26e22fcb9d4c54f0eac94916cda16cab6 and updated them in https://github.com/GlotPress/GlotPress-WP/pull/692/commits/20c96559153ab167cd591c9f860ad12f58283b29

In my research it showed that:
- 52 locales could not be found in CLDR (Afar `aa`, Avestan `ae`, Aragonese `an`, Avaric `av`, Aymara `ay`, Bashkir `ba`, Catalan (Balear) `bal`, Balochi Southern `bcc`, Bislama `bi`, Cebuano `ceb`, Chamorro `ch`, Corsican `co`, Cree `cr`, Kashubian `csb`, Church Slavic `cu`, Chuvash `cv`, Greek (Polytonic) `el-po`, Emoji `art-xemoji`, Fijian `fj`, Arpitan `frp`, Guaraní `gn`, Haitian Creole `hat`, Hazaragi `haz`, Interlingua `ia`, Ido `ido`, Iloko `ilo`, Kinyarwanda `kin`, Latin `la`, Limburgish `li`, Montenegrin `me`, Mari (Meadow) `mhr`, Maori `mri`, Mari (Hill) `mrj`, Mirandese `mwl`, Occitan `oci`, Rohingya `rhg`, Rusyn `rue`, Aromanian `rup`, Sanskrit `sa-in`, Sicilian `scn`, Sindhi `snd`, Sardinian `srd`, Sundanese `su`, Silesian `szl`, Tahitian `tah`, Tajik `tg`, Klingon `tlh`, Tatar `tt`, Tweants `twd`, Udmurt `udm`, Venetian `vec`, Mingrelian `xmf`).
- 13 locales had different plurals definitions in CLDR (Bambara `bm`, Breton `br`, Welsh `cy`, Indonesian `id`, Javanese `jv`, Lithuanian `lt`, Myanmar (Burmese) `mya`, Oromo `orm`, Sakha `sah`, Tagalog `tl`, Turkish `tr`, Turkmen `tuk`, Yoruba `yor`).

For the 13 cases I suggest to have native speakers review both nplurals and CLDR plurals rules, decide for the correct form and set the `cldr_plurals_mapping` accordingly.

All in all this PR is a much smaller implementation (the biggest part a maintenance [script](https://github.com/GlotPress/GlotPress-WP/pull/692/files#diff-265ed83e184ff54ae50b28e5db94e910)+[class](https://github.com/GlotPress/GlotPress-WP/pull/692/files#diff-e4ee6bf6c7a9c606abd4f3e341a2829b) that updates `locales.php` which doesn't run in production) and focusses on the main difference between the GlotPress (and gettext) style plurals format (integer index based) and CLDR (name based: zero, one, few, many, other).

A `cldr_plurals_mapping` of `array( 'one', 'other' )` means that gettext index 0 is `one` and index 1 is `other`.

### CODE REVIEW

**Comment by toolstack** [comment]
Won't work as some of our nplurals differ from the CLDR number of plurals.  Likewise our rules don't always map directly to a CLDR type.

**Comment by akirk** [comment]
I would like to ask you not to dismiss my efforts so quickly because of a number of edge cases (that you haven't named specifically). If CLDR has wrong data it's worth to contribute that information back to them. Additionally we could add any required override data to our GP_Locales and still use something along the lines of my implementation for the vast majority of cases where it does align.

**Comment by akirk** [comment]
I have now done some analysis regarding differences between our nplurals definitions and the cldr definitions: 13 locales (`bm`, `br`, `cy`, `id`, `jv`, `lt`, `mya`, `orm`, `sah`, `tl`, `tr`, `tuk`, `yor`) don't match, for the other 138 locales I can get a good mapping.

**Comment by akirk** [comment]
Sample Outputs for Russian, German, Arabic, and Japanese:

```
<?xml version="1.0" encoding="utf-8"?>
<!--
Translation-Revision-Date: 2016-03-02 17:19:19+0000
Generator: GlotPress/2.4.0-alpha
Language: ru
-->
<resources>
	<plurals name="_d_Theme_Update">
		<entry quantity="one">%d обновление темы</item>
		<entry quantity="few">%d обновления тем</item>
		<entry quantity="many">%d обновлений тем</item>
	</plurals>
</resources>
```

```
<?xml version="1.0" encoding="utf-8"?>
<!--
Translation-Revision-Date: 2016-03-02 17:19:19+0000
Generator: GlotPress/2.4.0-alpha
Language: de
-->
<resources>
	<plurals name="_d_Theme_Update">
		<entry quantity="one">%d Theme-Aktualisierung</item>
		<entry quantity="other">%d Theme-Aktualisierungen</item>
	</plurals>
</resources>
```

```
<?xml version="1.0" encoding="utf-8"?>
<!--
Translation-Revision-Date: 2016-04-05 13:01:59+0000
Generator: GlotPress/2.4.0-alpha
Language: ar
-->
<resources>
	<plurals name="_d_Theme_Update">
		<entry quantity="zero">%d قالب يحتاج تحديث</item>
		<entry quantity="one">%d قالب يحتاج تحديث</item>
		<entry quantity="two">%d قوالب تحتاج تحديث</item>
		<entry quantity="few">%d قوالب تحتاج تحديث</item>
		<entry quantity="many">%d قوالب تحتاج تحديث</item>
		<entry quantity="other">%d قوالب تحتاج تحديث</item>
	</plurals>
</resources>
```

```
<?xml version="1.0" encoding="utf-8"?>
<!--
Translation-Revision-Date: 2016-03-18 12:11:44+0000
Generator: GlotPress/2.4.0-alpha
Language: ja_JP
-->
<resources>
	<plurals name="_d_Theme_Update">
		<entry quantity="other">%d件のテーマ更新</item>
	</plurals>
</resources>
```

**Comment by toolstack** [comment]
Looks like there is a problem with some of the matching, for example in gettext Belarusian has 3 plurals while in CLDR it has four, but the algorithm only matches the three that have integer values (the fourth in CLDR has only decimal values).

There's also the question of how to handle the 13 locales that don't match, changing the gettext rules would be a significant impact to anyone who has translations already entered.  Likewise any time CLDR decides to change any of their plural mappings we'd have to update the gettext plural as well.

Also, for a locale like Belarusian that has a rule with no equivalent in gettext, there would have to be a way of indicating the rule is only for CLDR.

**Comment by akirk** [comment]
> Looks like there is a problem with some of the matching, for example in gettext Belarusian has 3 plurals while in CLDR it has four, but the algorithm only matches the three that have integer values (the fourth in CLDR has only decimal values).

I think my code is doing a valid assumption here. Gettext nplurals don't support decimal numbers. I see this PR as extending GlotPress with CLDR support, not changing GlotPress according to CLDR.

> There's also the question of how to handle the 13 locales that don't match, changing the gettext rules would be a significant impact to anyone who has translations already entered. Likewise any time CLDR decides to change any of their plural mappings we'd have to update the gettext plural as well.

Honestly I would go by user demand here. I could see simply not supporting CLDR for these 13 locales for now and work on them when we have users who need to export translations to iOS or Android.

**Comment by toolstack** [comment]
>I think my code is doing a valid assumption here. Gettext nplurals don't support decimal numbers. I see this PR as extending GlotPress with CLDR support, not changing GlotPress according to CLDR.

But it's not supporting all of the CLDR features so it's not really "supporting" CLDR.  Output for Belarusian in this case would create an invalid file as it would be missing the fourth group.

If we're supporting CLDR, we need to support all of it's features, not just those that align with gettext.

>Honestly I would go by user demand here. I could see simply not supporting CLDR for these 13 locales for now and work on them when we have users who need to export translations to iOS or Android.

Some of those locales are already in use for the iOS/Android WP apps and will be required pretty much from day one so waiting for user demand isn't really an option.  If we're going this direction, we need to have a plan in place to deal with them and the ongoing review/update with each new release of CLDR.

**Comment by toolstack** [comment]
Closing in favour of #784.

**Pull request closed without merging**
