### PR TITLE
Fix PHP error for parameter after optional parameter

### LINKED ISSUE #1446: PHP 8 issues with function parameter order
PHP 8 throws the following deprecation notices regarding the parameter order.

> PHP Deprecated: Required parameter $type follows optional parameter $object_id in /sites/translate.git-updater.com/files/wp-content/plugins/glotpress/gp-includes/meta.php on line 82
> PHP Deprecated: Required parameter $meta_key follows optional parameter $object_id in /sites/translate.git-updater.com/files/wp-content/plugins/glotpress/gp-includes/meta.php on line 168

### PR DESCRIPTION
**Pull request by afragen**
Fixes https://github.com/GlotPress/GlotPress/issues/1446

I'm not certain the changes to the unit tests are correct. I was unable to run phpunit according to the instruction for `wp-env` 😞

### CODE REVIEW

**Review by ocean90 — DISMISSED** [review]
Moving the object ID isn't really an option as it provides a bad DX.

Instead I think we should introduce new functions which handle the global meta:

```php
function gp_update_meta( $object_id, $meta_key, $meta_value, $type ) {}
function gp_update_global_meta( $meta_key, $meta_value, $type ) {}
function gp_delete_meta( $object_id, $meta_key, $meta_value, $type ) {}
function gp_delete_global_meta( $meta_key, $meta_value, $type ) {}
```

Thoughts?

**Comment by amieiro** [comment]
Why not only remove the default value, because you always have to use a value when you call to these functions?

```
function gp_update_meta( $object_id, $meta_key, $meta_value, $type, $global = false ) {
```


```
function gp_delete_meta( $object_id, $meta_key, $meta_value, $type, $global = false ) {
```

These changes pass the tests. I have just checked in my machine.

**Comment by akirk** [comment]
I agree with Jesús, since it's not possible to make use of the default value (`0`) of the first parameter, let's just remove it. @afragen Shall we close this and create a new PR or would you be willing to update it?

**Comment by afragen** [comment]
I should be able to update the PR for that.

**Review by akirk — APPROVED** [review]
Thank you! Looks good to me!

**Comment by amieiro** [comment]
@ocean90 is it ok if I dismiss your review, to merge this PR?

**Pull request merged**
