### PR TITLE
Add plural and plural forms labels to row previews and format the row editor accordingly

### LINKED ISSUE #1505: Add original plurals and labels to row preview plural strings
For plural strings, currently the row preview only shows the translation text plurals, the original text only shows the singular.
imagem

On [translate.wp.org template](https://github.com/WordPress/wordpress.org/blob/f63aa20a0b8ad126d758046c155f148fb0e6d6c2/wordpress.org/public_html/wp-content/plugins/wporg-gp-customizations/templates/translation-row-preview.php) both singular and plurals are shown in the original text, with "Singular" and "Plural" labels:
imagem

### PR DESCRIPTION
**Pull request by pedro-mendonca**
## What?
Add plurals to original in the translation row preview, and add plural forms labels, accordingly to translate.wp.org

## Why?
When filtering the Untranslated strings, there is no visual information about plural strings, either on original or translation column.
Example:
imagem

If the translation is added, only the translation shows the plural forms.
imagem

## How?
This PR adds the same logic to the template as the [template on wp.org](https://github.com/WordPress/wordpress.org/blob/f63aa20a0b8ad126d758046c155f148fb0e6d6c2/wordpress.org/public_html/wp-content/plugins/wporg-gp-customizations/templates/translation-row-preview.php), implementing this:
- [x] Add plural to original plural strings
- [x] Add Singular/Plural and other plural forms (e.g. Russian) to both original and translation texts
- [x] Vertical align to center the row plurals

Result for Singular/Plural (e.g.: Portuguese):
imagem

Result for other plural form (e.g.: Russian):
imagem

## Testing Instructions

1. Filter plural strings
2. See row preview with and without translation
3. Check it on languages with Singular/Plural and languages with othet plural forms (eg. Russian translation set)

Fixes #1505

### CODE REVIEW

**Comment by pedro-mendonca** [comment]
The commit https://github.com/GlotPress/GlotPress/pull/1506/commits/22e2856e9cf3d697bceb538b6b6d6810ff45f160 moves the Plural forms labels above the Original texts.

The commit https://github.com/GlotPress/GlotPress/pull/1506/commits/ac9d084190f0a62a84229ab66a4b68a02dedc1f6 removes the margin from the Plural form label and the Translation text.

Please check the comment https://github.com/GlotPress/GlotPress/issues/1505#issuecomment-1320218986 on the issue.

**Comment by pedro-mendonca** [comment]
Removed minified asset from the PR accordingly [this chat](https://wordpress.slack.com/archives/C02RP4R9F/p1678214215208689?thread_ts=1678211865.276979&cid=C02RP4R9F) with @amieiro about including minified assets.

The minified diffs is unreadable, and merging it creates conflicts with other pending PRs that are very difficult to keep up with.

It's better to build all the assets on the repo, after all the merge sessions are complete.

**Comment by akirk** [comment]
We agreed on our triage session that this can be merged after a code review. The functionality is fine.

**Review by amieiro — DISMISSED** [review]

**Comment by pedro-mendonca** [comment]
The PR is now again free of conflicts.

**Review by amieiro — APPROVED** [review]

**Pull request merged**
