### PR TITLE
860: Add term filter scope option.

### LINKED ISSUE #860: Include option for search Original or Translations only
If you want to find a bad translation and correct it, it would be very helpful to filter just the translations or Original strings.

For example "email" is translated to "E-Mail" in German, but many people use words like "email" or "Email" or "e-Mail". If I want to correct this, the "Any" filter is no help, because it is searching in the original string too, which gives me all strings which contain "mail", but I just want to find the bad spelling.

First reported here: https://glotpress.trac.wordpress.org/ticket/152

### PR DESCRIPTION
**Pull request by toolstack**
Resolves #860.

### CODE REVIEW

**Comment by toolstack** [comment]
scope

Comments on layout welcome :)

**Comment by garretthyder** [comment]
Thanks @toolstack 

The inputs and the term scope seem to be misaligned from their labels there.

And I wonder if it can be cleaned up a bit giving 'term' a dedicated column now that it has the input and the radio group. Something like this;
screen shot 2018-10-04 at 10 07 42 am

Or if Term should have precedence maybe;
screen shot 2018-10-04 at 10 08 25 am

And I noticed the box is displaced on your screen as it's wider and wonder if the bulk actions should have their own row so that the filter/sort/statuses are always on their own row and left aligned as sometimes like in your view the filter/sort boxes feel out of place when they appear in the middle of the page instead of left aligned.

**Comment by toolstack** [comment]
Yeah, the misalignment of the labels is a Firefox weirdness because the filters dropdown uses paragraph tags I think.

The box is displaced because it starts where ever the filter "button" is on the screen, so that's by design.

I'm not sure about splitting the rows, it makes the important stuff (the translations) appear even farther down the screen.

**Comment by toolstack** [comment]
How about something like this:

current filter

**Comment by toolstack** [comment]
Minor updates to the above suggestion:

Firefox:
current filter

Vivaldi:
chrome

**Comment by garretthyder** [comment]
Thanks @toolstack I do like the update with Options as a label and the label being above avoids the misalignment on FF.

As to
> The box is displaced because it starts where ever the filter "button" is on the screen, so that's by design.
> I'm not sure about splitting the rows, it makes the important stuff (the translations) appear even farther down the screen.

I opened #942 to discuss this as I feel it's jarring when displaced like that and wouldn't push the translations much further down (maybe 20px).

**Review by Mte90 — APPROVED** [review]
Tested, deserve a mention on the blog that feature because help a lot on searching bad translation also for consitency as example.

**Comment by toolstack** [comment]
@mte90 I'm dreading writing the change log and post for 3.0 ;)

I did mention it in today's post, I'm thinking for the 3.0 release we might have to do a few posts over the lead up to 3.0.  Maybe one for "UI Improvements" like this, one for Variants, one for CLDR and a few others to cover off all the new stuff :smile:.

**Comment by Mte90** [comment]
Good idea so we can promote all the changes!

**Comment by pedro-mendonca** [comment]
Hi @toolstack
I know I’m probably late.
But why are these terms choices radio buttons instead of checkboxes?
It would allow a much more flexible selection of scope, instead of only the existent combinations.

Example: it’s not possible to choose simultaneously Originals and Context

**Comment by toolstack** [comment]
@pedro-mendonca primarily due to the complexity of the SQL statement, but it could be done.

**Comment by pedro-mendonca** [comment]
Hi @toolstack and @Mte90 
I understand it might increase the complexity of the SQL statement, but it will give much more power to GlotPress search and usability.
Here is my late suggestion:

screenshot 2018-10-17 15 21 41

The layout is organized by priorities, of most used items, with most common items checked:


#### Main search fields
 - Term
 - User
 - Search button

#### Search scope
 - Originals - search **in** originals
 - Translations - search **in** translations
 - Contexts - search **in** contexts
 - Comments - search **in** comments
 - References - search **in** References

#### Status - filters which status to include in the search
 - Current
 - Waiting
 - Fuzzy
 - Untranslated
 - Obsolete
 - Rejected

#### Options
 - With comment - entries **with** comments
 - With context - entries **with** context
 - With warnings - entries **with** warnings
 - Case sensitive

**Comment by Mte90** [comment]
Maybe we can implement as it is for 3.0 release and in the next version improving also with gathering of feedbacks from the community so we can see what are the problems.
I am afraid that in networks like translate.wp.org can be very slow because the database is huge so is better to see that feature in action in this situation before do advanced changes.

**Comment by pedro-mendonca** [comment]
All the options above already exist in GP, it's just not possible to filter for some of them individualy.

**Comment by toolstack** [comment]
I think the idea of allowing a mix of search scope makes sense, but the suggested layout doesn't quite work, for example you can't search for a user in a context :smile: 

If you want to create a PR (and issue) for this change it might make it in to 3.0, but otherwise we can take a look at this for a future release.

**Comment by pedro-mendonca** [comment]
You're right, the Search scope applies only to Term input.

**Comment by pedro-mendonca** [comment]
@toolstack I've separated the user as some of the suggestions above, and opened the issue #955

**Pull request merged**
