### PR TITLE
Local GlotPress

### PR DESCRIPTION
**Pull request by akirk**
This comprises of the PRs that make up Local GlotPress:

- #1567
- #1573
- #1576
- #1577
- #1578
- #1579
- #1581
- #1595
- #1596
- #1602
- #1603

### CODE REVIEW

**Comment by akirk** [comment]
I have tested this on translate.wordpress.org

**Review by trymebytes — APPROVED** [review]
Also tested on translate.wordpress.org and no issues.

**Review by ocean90 — DISMISSED** [review]
Just noting that this should not be merged into the current milestone 4.0. There should be one last stable version (4.0) which doesn't have all these "Local GlotPress" changes. Once that's done this can be probably merged as a focus of a 5.0 release.

**Review by amieiro — APPROVED** [review]
I have tested and works for me! Nice job!

**Pull request merged**
